---
- name: retrieve kubeconfig file 
  hosts: k3s 
  tasks: 
    - name: copy file kubeconfig 
      fetch: 
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig-k3s.yml
        flat: yes
    - name: modify kubecongi file 
      local_action: 
        module: lineinfile
        path: ./kubeconfig-k3s.yml
        regexp: '    server: https://127.0.0.1:6443'
        line: '    server: https://{{ ansible_host }}:6443'