---
# tasks file for pgdamin
- name: generate docker compose
  template:
    src: "pgadmin-compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/pgadmin-compose.yaml"
    mode: "0555"

- name: start pgadmin stack
  command: " docker compose -f /home/{{ ansible_user }}/pgadmin-compose.yaml up -d"